import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Result object to pass back to UI
class ValidationResult {
  final bool isValid;
  final int? energy;
  final String? errorMessage;

  ValidationResult({required this.isValid, this.energy, this.errorMessage});

  static ValidationResult success(int energy) =>
      ValidationResult(isValid: true, energy: energy);

  static ValidationResult failure(String error) =>
      ValidationResult(isValid: false, errorMessage: error);
}

class RewardCodeValidator {
  // MUST MATCH THE JS "REWARD_SECRET_KEY" EXACTLY
  static const String _secretKey = "NX26";
  static const String _usedCodesKey = "used_reward_codes";

  /// 1. Main Function to Validate
  static Future<ValidationResult> validateAndRedeemCode(String code) async {
    try {
      code = code.trim(); // Remove whitespace

      // A. Check Format (Payload.Signature)
      if (!code.contains('.')) {
        return ValidationResult.failure('Invalid Code Format');
      }
      final parts = code.split('.');
      if (parts.length != 2) return ValidationResult.failure('Corrupted Code');

      final payloadB64 = parts[0];
      final signatureB64 = parts[1];

      // B. Verify Signature (The Security Check)
      final calculatedSig = _calculateHMAC(payloadB64, _secretKey);

      // Compare the signature generated by JS vs Dart
      if (calculatedSig != signatureB64) {
        return ValidationResult.failure('Invalid Signature (Fake Key)');
      }

      // C. Decode Payload
      final payloadJson = _base64UrlDecode(payloadB64);
      final Map<String, dynamic> payload = jsonDecode(payloadJson);

      // D. Check Expiry
      final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
      final exp = (payload['exp'] as num).toInt();

      if (now > exp) {
        return ValidationResult.failure('Code Expired');
      }

      // E. Check for Reuse (Prevent double dipping)
      final isUsed = await _isCodeUsed(code);
      if (isUsed) {
        return ValidationResult.failure('Code Already Used');
      }

      // F. Get Energy
      final energy = (payload['e'] as num).toInt();

      // G. Mark as used PERMANENTLY
      await _markCodeAsUsed(code);

      return ValidationResult.success(energy);
    } catch (e) {
      return ValidationResult.failure('Error: $e');
    }
  }

  // --- Helpers ---

  // Replicates CryptoJS.HmacSHA256 logic
  static String _calculateHMAC(String message, String secret) {
    List<int> keyBytes = utf8.encode(secret);
    List<int> msgBytes = utf8.encode(message);
    Hmac hmac = Hmac(sha256, keyBytes);
    Digest digest = hmac.convert(msgBytes);

    // Convert to Base64 and then make it URL-safe (replace + with -, / with _)
    String base64 = base64Encode(digest.bytes);
    return base64.replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '');
  }

  // Replicates atob() with padding fix
  static String _base64UrlDecode(String input) {
    String base64 = input.replaceAll('-', '+').replaceAll('_', '/');
    while (base64.length % 4 != 0) {
      base64 += '=';
    }
    return utf8.decode(base64Decode(base64));
  }

  // Anti-Replay System
  static Future<bool> _isCodeUsed(String code) async {
    final prefs = await SharedPreferences.getInstance();
    final usedList = prefs.getStringList(_usedCodesKey) ?? [];
    // We store the hash of the code to save space
    final codeHash = sha256.convert(utf8.encode(code)).toString();
    return usedList.contains(codeHash);
  }

  static Future<void> _markCodeAsUsed(String code) async {
    final prefs = await SharedPreferences.getInstance();
    final usedList = prefs.getStringList(_usedCodesKey) ?? [];
    final codeHash = sha256.convert(utf8.encode(code)).toString();

    if (!usedList.contains(codeHash)) {
      usedList.add(codeHash);
      await prefs.setStringList(_usedCodesKey, usedList);
    }
  }
}
